// lib/constants/patterns.ts
// Patrones de respiración — valores calibrados, NO modificar sin prueba auditiva

import type { BreathPattern } from '@/types'

export const BREATH_PATTERNS: BreathPattern[] = [
  {
    id: 0,
    nombre: 'Sueño Delta',
    nivel: 1,
    emoji: '🌊',
    color: 'rgba(75,85,185,0.18)',
    descripcion: 'Fase más profunda del sueño · inhala 4s · pausa 2s · exhala 8s',
    descripcionLarga: 'Reproduce la respiración de la fase delta, la más reparadora. Tan lento que tu cerebro decide que es mejor dormirse que mantener ese ritmo despierto.',
    inhala: 4,
    pausa: 2,
    exhala: 8,
    rpm: 4.3,
    audio: {
      inhale: {
        bandpassFreq:  1100,
        bandpassQ:     0.55,
        lowpassFreq:   [2800, 3200],
        highpassFreq:  200,
        volume:        0.55,
        attackRatio:   0.20,
        releaseRatio:  0.30,
        oscFreq:       [130, 170],
        oscVolume:     0.10,
      },
      exhale: {
        bandpassFreq:  650,
        bandpassQ:     0.40,
        lowpassFreq:   [1800, 1400],
        highpassFreq:  80,
        volume:        0.45,
        attackRatio:   0.10,
        releaseRatio:  0.45,
        oscFreq:       [95, 75],
        oscVolume:     0.07,
      },
    },
  },
  {
    id: 1,
    nombre: 'Sueño Profundo',
    nivel: 2,
    emoji: '🌙',
    color: 'rgba(105,80,190,0.18)',
    descripcion: 'Sueño consolidado · inhala 4s · pausa 2s · exhala 6s',
    descripcionLarga: 'La respiración del sueño no-REM profundo. Activa el nervio vago y baja la frecuencia cardíaca de forma progresiva.',
    inhala: 4,
    pausa: 2,
    exhala: 6,
    rpm: 5,
    audio: {
      inhale: {
        bandpassFreq:  1050,
        bandpassQ:     0.52,
        lowpassFreq:   [2600, 3000],
        highpassFreq:  190,
        volume:        0.52,
        attackRatio:   0.20,
        releaseRatio:  0.32,
        oscFreq:       [125, 165],
        oscVolume:     0.095,
      },
      exhale: {
        bandpassFreq:  680,
        bandpassQ:     0.42,
        lowpassFreq:   [1900, 1500],
        highpassFreq:  85,
        volume:        0.43,
        attackRatio:   0.11,
        releaseRatio:  0.43,
        oscFreq:       [98, 78],
        oscVolume:     0.072,
      },
    },
  },
  {
    id: 2,
    nombre: 'Adormecimiento',
    nivel: 3,
    emoji: '✨',
    color: 'rgba(65,110,185,0.18)',
    descripcion: 'Inicio del sueño ligero · inhala 5s · exhala 5s',
    descripcionLarga: 'Respiración de coherencia cardíaca. Seis respiraciones por minuto es la frecuencia de resonancia del sistema nervioso autónomo.',
    inhala: 5,
    pausa: 0,
    exhala: 5,
    rpm: 6,
    audio: {
      inhale: {
        bandpassFreq:  1000,
        bandpassQ:     0.50,
        lowpassFreq:   [2400, 2800],
        highpassFreq:  180,
        volume:        0.50,
        attackRatio:   0.22,
        releaseRatio:  0.30,
        oscFreq:       [120, 160],
        oscVolume:     0.085,
      },
      exhale: {
        bandpassFreq:  700,
        bandpassQ:     0.44,
        lowpassFreq:   [2000, 1600],
        highpassFreq:  90,
        volume:        0.40,
        attackRatio:   0.12,
        releaseRatio:  0.40,
        oscFreq:       [100, 80],
        oscVolume:     0.068,
      },
    },
  },
  {
    id: 3,
    nombre: 'Relajación',
    nivel: 4,
    emoji: '🍃',
    color: 'rgba(95,155,185,0.18)',
    descripcion: 'El más natural · inhala 4s · exhala 4s',
    descripcionLarga: 'Empieza aquí si los otros te agobían. Aún así es mucho más lento de lo habitual y activa la respuesta de relajación del sistema nervioso parasimpático.',
    inhala: 4,
    pausa: 0,
    exhala: 4,
    rpm: 7.5,
    audio: {
      inhale: {
        bandpassFreq:  950,
        bandpassQ:     0.48,
        lowpassFreq:   [2200, 2600],
        highpassFreq:  170,
        volume:        0.48,
        attackRatio:   0.22,
        releaseRatio:  0.28,
        oscFreq:       [115, 155],
        oscVolume:     0.082,
      },
      exhale: {
        bandpassFreq:  720,
        bandpassQ:     0.45,
        lowpassFreq:   [2100, 1700],
        highpassFreq:  95,
        volume:        0.38,
        attackRatio:   0.13,
        releaseRatio:  0.38,
        oscFreq:       [102, 82],
        oscVolume:     0.065,
      },
    },
  },
]

export const getPatternById = (id: number): BreathPattern | undefined =>
  BREATH_PATTERNS.find(p => p.id === id)
