// lib/db.ts — Database abstraction layer
// Uses PostgreSQL (RDS) via lib/postgres/db.ts

export {
  insertUser,
  getUsers,
  getUserById,
  updateUser,
  getUsersWithStats,
  insertSession,
  updateSession,
  getSessionsByUser,
  getMostUsedPattern,
  getDashboardSummary,
  getByGenero,
  getByEdad,
  getByMedicacion,
  getByTecnica,
  getByHoras,
  // Sessions
  getAllSessions,
  getSessionsSummary,
  getSessionsByTecnica,
  getSessionsByDay,
  getSessionsByHour,
  getEngagementDistribution,
  // Correlations
  getTecnicaByGenero,
  getTecnicaByEdad,
  getTecnicaByMedicacion,
  getCompletionByMedicacion,
  getDuracionByEdad,
  getHorasSuenoByTecnica,
  getMedicacionByHorasSueno,
  // Geographic
  getUsersByCountry,
  getUsersByCiudad,
  getSessionsByCountry,
  getGeoTable,
  // Blog
  insertBlogPost,
  getBlogPosts,
  getPublishedBlogPosts,
  getBlogPostById,
  getBlogPostBySlug,
  updateBlogPost,
  deleteBlogPost,
  // Retreats
  insertRetreat,
  getRetreats,
  getPublishedRetreats,
  getRetreatById,
  updateRetreat,
  deleteRetreat,
  // Retreat registrations
  getRetreatRegistrationCount,
  getUserRetreatRegistrations,
  registerForRetreat,
  getRetreatRegistrations,
} from './postgres/db'
